# map category name to icon
categoryIcon:
  "Database & Cache": "database"
  "Prometheus Exporter": "export"
  "Networking": "router"
  "Storage": "storage"
  "Image Registry": "cdn"
  "Big Data": "increase"
  "Message Queueing": "blockchain"
  "Web Server": "ip"
  "CI/CD": "abtest"
  "Monitoring & Logging": "monitor"
  "Security": "shield"
  "AI/ML": "ai"
  "CMS": "record"
appCategory:
  mariadb: "Database & Cache"
  mariadb-galera: "Database & Cache"
  mysql: "Database & Cache"
  postgresql: "Database & Cache"
  postgresql-ha: "Database & Cache"
  mongodb: "Database & Cache"
  mongodb-sharded: "Database & Cache"
  redis: "Database & Cache"
  redis-cluster: "Database & Cache"
  valkey: "Database & Cache"
  valkey-cluster: "Database & Cache"
  keydb: "Database & Cache"
  memcached: "Database & Cache"
  cassandra: "Database & Cache"
  scylladb: "Database & Cache"
  neo4j: "Database & Cache"
  clickhouse: "Database & Cache"
  clickhouse-operator: "Database & Cache"
  cloudnative-pg: "Database & Cache"
  influxdb: "Database & Cache"
  etcd: "Database & Cache"
  janusgraph: "Database & Cache"
  kube-arangodb: "Database & Cache"

  kube-state-metrics: "Prometheus Exporter"
  node-exporter: "Prometheus Exporter"
  cadvisor: "Prometheus Exporter"
  kubernetes-event-exporter: "Prometheus Exporter"

  nginx-ingress-controller: "Networking"
  contour: "Networking"
  kong: "Networking"
  apisix: "Networking"
  envoy-gateway: "Networking"
  haproxy: "Networking"
  metallb: "Networking"
  cilium: "Networking"
  multus-cni: "Networking"
  whereabouts: "Networking"
  external-dns: "Networking"
  oauth2-proxy: "Networking"
  kubelb-manager: "Networking"
  kubelb-ccm: "Networking"

  minio: "Storage"
  minio-operator: "Storage"
  seaweedfs: "Storage"

  harbor: "Image Registry"

  spark: "Big Data"
  flink: "Big Data"
  dremio: "Big Data"
  elasticsearch: "Big Data"
  opensearch: "Big Data"
  milvus: "Big Data"
  superset: "Big Data"
  kuberay: "AI/ML"
  solr: "Big Data"
  nessie: "Big Data"
  airflow: "Big Data"

  rabbitmq: "Message Queueing"
  rabbitmq-cluster-operator: "Message Queueing"
  kafka: "Message Queueing"
  nats: "Message Queueing"
  schema-registry: "Message Queueing"
  zookeeper: "Message Queueing"

  nginx: "Web Server"
  apache: "Web Server"
  tomcat: "Web Server"
  wildfly: "Web Server"
  aspnet-core: "Web Server"

  # 추가 카테고리 예시
  jenkins: "CI/CD"
  argo-cd: "CI/CD"
  argo-workflows: "CI/CD"
  flux: "CI/CD"
  concourse: "CI/CD"
  gitea: "CI/CD"
  gitlab-runner: "CI/CD"
  sonarqube: "CI/CD"

  prometheus: "Monitoring & Logging"
  kube-prometheus: "Monitoring & Logging"
  grafana: "Monitoring & Logging"
  grafana-loki: "Monitoring & Logging"
  grafana-alloy: "Monitoring & Logging"
  grafana-mimir: "Monitoring & Logging"
  grafana-operator: "Monitoring & Logging"
  grafana-tempo: "Monitoring & Logging"
  grafana-k6-operator: "Monitoring & Logging"
  fluentd: "Monitoring & Logging"
  fluent-bit: "Monitoring & Logging"
  logstash: "Monitoring & Logging"
  kibana: "Monitoring & Logging"
  jaeger: "Monitoring & Logging"
  zipkin: "Monitoring & Logging"
  victoriametrics: "Monitoring & Logging"
  thanos: "Monitoring & Logging"
  metrics-server: "Monitoring & Logging"

  cert-manager: "Security"
  sealed-secrets: "Security"
  vault: "Security"
  keycloak: "Security"
  pinniped: "Security"
  kiam: "Security"
  ejbca: "Security"
  chainloop: "Security"

  jupyterhub: "AI/ML"
  mlflow: "AI/ML"
  pytorch: "AI/ML"
  deepspeed: "AI/ML"
  tensorflow-resnet: "AI/ML"

  wordpress: "CMS"
  drupal: "CMS"
  ghost: "CMS"
  moodle: "CMS"
  redmine: "CMS"
  discourse: "CMS"
  mastodon: "CMS"
  matomo: "CMS"
  prestashop: "CMS"
  phpbb: "CMS"
  joomla: "CMS"
appNameReplace:
  "argo-workflows": "Argo Workflows"
  "opensearch": "OpenSearch"
  "elasticsearch": "Elasticsearch"
  "envoy-gateway": "Envoy Gateway"
  "etcd": "ETCD"
  "kube-prometheus": "Prometheus Operator"
  "kube-state-metrics": "kube-state-metrics"
  "aspnet-core": "ASP.NET core"
  "cadvisor": "cAdvisor"
  "prestashop": "PrestaShop"
  "logstash": "Logstash"
  "jaeger": "Jaeger"
  "nats": "NATS"
  "gitea": "Gitea"
  "gitlab-runner": "Gitlab Runner"
  "wordpress": "WordPress"
  "supabase": "Supabase"
  "prometheus": "Prometheus"
  "jupyterhub": "JupyterHub"
  "kibana": "Kibana"
  "mariadb": "MariaDB"
  "ejbca": "EJBCA"
  "grafana-loki": "Grafana Loki"
  "grafana-alloy": "Grafana Alloy"
  "grafana-k6-operator": "Grafana K6 Operator"
  "grafana-operator": "Grafana Operator"
  "wildfly": "Wildfly"
  "zipkin": "Zipkin"
  "spark": "Spark"
  "superset": "Superset"
  "zookeeper": "ZooKeeper"
  "milvus": "Milvus"
  "pytorch": "PyTorch"
  "rabbitmq": "RabbitMQ"
  "rabbitmq-cluster-operator": "RabbitMQ Cluster Operator"
  "mlflow": "MLflow"
  "flux": "Flux"
  "metallb": "MetalLB"
  "phpmyadmin": "phpMyAdmin"
  "sonarqube": "SonarQube"
  "argo-cd": "ArgoCD"
  "discourse": "Discourse"
  "dremio": "Dremio"
  "solr": "Solr"
  "influxdb": "InfluxDB"
  "grafana-tempo": "Grafana Tempo"
  "oauth2-proxy": "OAuth2 Proxy"
  "contour": "Contour"
  "janusgraph": "JanusGraph"
  "consul": "Consul"
  "haproxy": "HAProxy"
  "redmine": "Redmine"
  "kubernetes-event-exporter": "Kubernetes Event Exporter"
  "kiam": "Kiam"
  "airflow": "Airflow"
  "phpbb": "phpBB"
  "concourse": "Concourse"
  "flink": "Flink"
  "apache": "Apache"
  "tensorflow-resnet": "TensorFlow ResNet"
  "matomo": "Matomo"
  "kuberay": "KubeRay"
  "memcached": "Memcached"
  "grafana-mimir": "Grafana Mimir"
  "kong": "Kong"
  "kube-arangodb": "ArangoDB Kubernetes Operator"
  "sealed-secrets": "Sealed Secrets"
  "seaweedfs": "SeaweedFS"
  "fluentd": "Fluentd"
  "cassandra": "Cassandra"
  "vault": "Vault"
  "victoriametrics": "Victoria Metrics"
  "whereabouts": "Whereabouts"
  "clickhouse": "ClickHouse"
  "clickhouse-operator": "ClickHouse Operator"
  "cloudnative-pg": "CloudNativePG"
  "schema-registry": "Schema Registry"
  "scylladb": "ScyllaDB"
  "moodle": "Moodle"
  "multus-cni": "Multus CNI"
  "external-dns": "ExternalDNS"
  "fluent-bit": "Fluent Bit"
  "thanos": "Thanos"
  "nginx-ingress-controller": "NGINX Ingress Controller"
  "mastodon": "Mastodon"
  "cert-manager": "CertManager"
  "chainloop": "Chainloop"
  "cilium": "Cilium"
  "kafka": "Kafka"
  "pinniped": "Pinniped"
  "parse": "Parse"
  "appsmith": "Appsmith"
  "jenkins": "Jenkins"
  "osclass": "Osclass"
  "odoo": "Odoo"
  "ghost": "Ghost"
  "keycloak": "Keycloak"
  "keydb": "KeyDB"
  "kiam": "Kiam"
  "drupal": "Drupal"
  "grafana": "Grafana"
  "deepspeed": "DeepSpeed"
  "metrics-server": "Metrics Server"
  "mariadb-galera": "MariaDB Galera"
  "postgresql": "PostgreSQL"
  "postgresql-ha": "PostgreSQL HA"
  "minio": "MinIO"
  "minio-operator": "MinIO Operator"
  "apisix": "APISIX"
  "nginx": "NGINX"
  "node-exporter": "Node Exporter" 
  "tomcat": "Tomcat"
  "valkey": "Valkey"
  "valkey-cluster": "Valkey Cluster"
  "rabbitmq": "RabbitMQ"
  "mysql": "MySQL"
  "neo4j": "Neo4J"
  "nessie": "Nessie"
  "mongodb": "MongoDB"
  "mongodb-sharded": "MongoDB Sharded"
  "redis": "Redis"
  "redis-cluster": "Redis Cluster"
  "harbor": "Harbor"
  "kubelb-manager": "KubeLB Manager"
  "kubelb-ccm": "KubeLB Cloud Controller Manager"
