# map category name to icon
categoryIcon:
  "Database & Cache": "database"
  "Prometheus Exporter": "export"
  "Networking": "router"
  "Storage": "storage"
  "Image Registry": "cdn"
  "Big Data": "increase"
  "Message Queueing": "blockchain"
  "Web Server": "ip"
appNameReplace:
  "argo-workflows": "Argo Workflows"
  "opensearch": "OpenSearch"
  "elasticsearch": "Elasticsearch"
  "envoy-gateway": "Envoy Gateway"
  "etcd": "ETCD"
  "kube-prometheus": "Prometheus Operator"
  "kube-state-metrics": "kube-state-metrics"
  "aspnet-core": "ASP.NET core"
  "cadvisor": "cAdvisor"
  "prestashop": "PrestaShop"
  "logstash": "Logstash"
  "jaeger": "Jaeger"
  "nats": "NATS"
  "gitea": "Gitea"
  "gitlab-runner": "Gitlab Runner"
  "wordpress": "WordPress"
  "supabase": "Supabase"
  "prometheus": "Prometheus"
  "jupyterhub": "JupyterHub"
  "kibana": "Kibana"
  "mariadb": "MariaDB"
  "ejbca": "EJBCA"
  "grafana-loki": "Grafana Loki"
  "grafana-alloy": "Grafana Alloy"
  "grafana-k6-operator": "Grafana K6 Operator"
  "grafana-operator": "Grafana Operator"
  "wildfly": "Wildfly"
  "zipkin": "Zipkin"
  "spark": "Spark"
  "superset": "Superset"
  "zookeeper": "ZooKeeper"
  "milvus": "Milvus"
  "pytorch": "PyTorch"
  "rabbitmq": "RabbitMQ"
  "rabbitmq-cluster-operator": "RabbitMQ Cluster Operator"
  "mlflow": "MLflow"
  "flux": "Flux"
  "metallb": "MetalLB"
  "phpmyadmin": "phpMyAdmin"
  "sonarqube": "SonarQube"
  "argo-cd": "ArgoCD"
  "discourse": "Discourse"
  "dremio": "Dremio"
  "solr": "Solr"
  "influxdb": "InfluxDB"
  "grafana-tempo": "Grafana Tempo"
  "oauth2-proxy": "OAuth2 Proxy"
  "contour": "Contour"
  "janusgraph": "JanusGraph"
  "consul": "Consul"
  "haproxy": "HAProxy"
  "redmine": "Redmine"
  "kubernetes-event-exporter": "Kubernetes Event Exporter"
  "kiam": "Kiam"
  "airflow": "Airflow"
  "phpbb": "phpBB"
  "concourse": "Concourse"
  "flink": "Flink"
  "apache": "Apache"
  "tensorflow-resnet": "TensorFlow ResNet"
  "matomo": "Matomo"
  "kuberay": "KubeRay"
  "memcached": "Memcached"
  "grafana-mimir": "Grafana Mimir"
  "kong": "Kong"
  "kube-arangodb": "ArangoDB Kubernetes Operator"
  "sealed-secrets": "Sealed Secrets"
  "seaweedfs": "SeaweedFS"
  "fluentd": "Fluentd"
  "cassandra": "Cassandra"
  "vault": "Vault"
  "victoriametrics": "Victoria Metrics"
  "whereabouts": "Whereabouts"
  "clickhouse": "ClickHouse"
  "clickhouse-operator": "ClickHouse Operator"
  "cloudnative-pg": "CloudNativePG"
  "schema-registry": "Schema Registry"
  "scylladb": "ScyllaDB"
  "moodle": "Moodle"
  "multus-cni": "Multus CNI"
  "external-dns": "ExternalDNS"
  "fluent-bit": "Fluent Bit"
  "thanos": "Thanos"
  "nginx-ingress-controller": "NGINX Ingress Controller"
  "mastodon": "Mastodon"
  "cert-manager": "CertManager"
  "chainloop": "Chainloop"
  "cilium": "Cilium"
  "kafka": "Kafka"
  "pinniped": "Pinniped"
  "parse": "Parse"
  "appsmith": "Appsmith"
  "jenkins": "Jenkins"
  "osclass": "Osclass"
  "odoo": "Odoo"
  "ghost": "Ghost"
  "keycloak": "Keycloak"
  "keydb": "KeyDB"
  "kiam": "Kiam"
  "drupal": "Drupal"
  "grafana": "Grafana"
  "deepspeed": "DeepSpeed"
  "metrics-server": "Metrics Server"
  "mariadb-galera": "MariaDB Galera"
  "postgresql": "PostgreSQL"
  "postgresql-ha": "PostgreSQL HA"
  "minio": "MinIO"
  "minio-operator": "MinIO Operator"
  "apisix": "APISIX"
  "nginx": "NGINX"
  "node-exporter": "Node Exporter" 
  "tomcat": "Tomcat"
  "valkey": "Valkey"
  "valkey-cluster": "Valkey Cluster"
  "rabbitmq": "RabbitMQ"
  "mysql": "MySQL"
  "neo4j": "Neo4J"
  "nessie": "Nessie"
  "mongodb": "MongoDB"
  "mongodb-sharded": "MongoDB Sharded"
  "redis": "Redis"
  "redis-cluster": "Redis Cluster"
  "harbor": "Harbor"
  "kubelb-manager": "KubeLB Manager"
  "kubelb-ccm": "KubeLB Cloud Controller Manager"
